### PR TITLE
Fix pulp CI tests failing for 2 different reasons

### LINKED ISSUE #584: Pulp docker image tags for releases after pulp 3.43.1 missing
At https://hub.docker.com/r/pulp/pulp docker image tags for pulp releases after 3.43.1 are missing:
https://hub.docker.com/r/pulp/pulp/tags?page=1&name=3.4

### LINKED ISSUE #588: pulp_tests.sh in CI fails to build openshift-examples/web.git
Our CI tests for the Pulp images tries and fails to build https://github.com/openshift-examples/web.git for about the last month or so. We build it because it is an example of running buildah within a container. In other words, nested buildah.

This appears to be due to upstream breakage, building an older commit works.

### PR DESCRIPTION
**Pull request by mikedep333**
Fixes: #584

Fixes: #588

Note: Galaxy tests are still failing due to python version, which is a much larger endeavor under way.

### CODE REVIEW

**Comment by netsandbox** [comment]
If you install now pulp-cli with pip, is then the git clone of the pulp-cli repo still needed?

**Comment by mikedep333** [comment]
> If you install now pulp-cli with pip, is then the git clone of the pulp-cli repo still needed?

Hey @netsandbox there's probably a more efficient way to do it. But we still install the test_requirements .

**Comment by mikedep333** [comment]
@netsandbox Also, when I tried installing the folder, it didn't work. It thought it was installing package "UNKNOWN" . And the `pulp` binary was still not found.

File: images/s6_assets/pulp_tests.sh [hunk 1]
```diff
@@ -21,6 +21,7 @@ else
   cd pulp-cli
 fi
 pip install -r test_requirements.txt || pip install --no-build-isolation -r test_requirements.txt
```
Comment (mdellweg) [inline images/s6_assets/pulp_tests.sh:23]: Is this script meant to be run inside the container? Let's not do that.
By calling pip, we may end up with an incompatible version of pulp-glue for pulpcore.

Instead, I suggest: Install the cli, retrieve it's version and checkout the corresponding release tag to grant access to the matching test suite.

Comment (mikedep333) [reply images/s6_assets/pulp_tests.sh:23]: @mdellweg No it's not. It is run on the host.

**Review by dkliban — APPROVED** [review]
